CONNEXION PROF/GRAPH PROF/GRAPH ETUDIANT
LouisSeranne/DICJ_Stimulus_A23 pull request #128
Opened 2023-10-20 12:20 UTC by Marc-Antoine-B

**PATCHNOTE PRE-SPRINT 3**

**CHANGEMENT CODE**
_Nouveaux fichiers :_
HeaderComponentEtudiant (Contient la session etudiante et le header)
HeaderComponentProf (Contient la session prof et le header)
GraphComponentEtudiant (Contient le graph etudiant)
GraphComponentProf (Contient le graph prof)
NoeudProf (Contient les noeuds pour le graph prof)
NoeudEtudiant (Contient les noeuds pour le graph etudiant)
NonDraggable (Permet de ne pas pouvoir draggable (pour l'étudiant))
ProfesseurLayout (Charge le header,graph et footer du prof)

**AJOUT**
Connexion avec un professeur  (Actuellement un peu hardcodé en attendeant la nouvelle bd) utiliser le prof : 1111111 MDP : Password123!
Graph Etudiant fonctionnelle avec fonctions de base et redirection des noeuds vers des pages
Graph Prof fonctionnelle et modifiable à souhait avec plusieurs options de vue (à vous de découvrir) Pas terminé

**CHANGEMENT API**
Ajout du champ NumEmploye dans Professeur, qui fait référence à num_employe dans la BD. Elle est en API local actuellement

**CHANGEMENT BD**
Ajout de la colonne num_employe     varchar(255)    NULL  dans la table professeur (actuellement intégré à la BD : TestStimulusProjet_Evolution)

2023-10-20 14:49 UTC, YohanTremblay requested changes
1. On doit encore refresh pour voir le graph quand on se connecte pour la première fois
2. Pourquoi il y a un noeud qui n'est pas dans un rond ? (Test1 - TestGroup)

![image](https://github.com/LouisSeranne/DICJ_Stimulus_A23/assets/89463262/9dd49798-8046-4ac3-ba42-097939825c97)

Pourquoi quand on monte un petit peu on voit un espèce de rebord qui passe par dessus les noeuds 

![image](https://github.com/LouisSeranne/DICJ_Stimulus_A23/assets/89463262/57051309-2a3c-4c2a-abd5-4eea68070512)

3. Une idée de pourquoi le front crash quand on va dans une balise de code ?

![image](https://github.com/LouisSeranne/DICJ_Stimulus_A23/assets/89463262/21a4b184-fc5a-4029-887a-bb83d16e9703)

2023-10-22 18:13 UTC, Marc-Antoine-B commented
problème #3 : HTTP 400 réglé mais j'ai une nouvelle erreur HTTP 500 venant de PageExercicePOSTAsync cette fois,, si vous avez une idée du problème

2023-10-22 18:18 UTC, Marc-Antoine-B commented
problème #1 : Réglé, c'était notre ancienne requête qui était encore dans le composant, j'ai ajouter celle de Corentin pour le prof et j'ai modifier pour qu'elle se redirige vers /index !

2023-10-24 14:23 UTC, YohanTremblay requested changes
Les 3 boutons dans le header sont décalés vers la gauche,
![image](https://github.com/LouisSeranne/DICJ_Stimulus_A23/assets/89463262/df0ab5bb-f67c-4c59-88bb-34a1f2a8fbb4)

2023-10-24 14:30 UTC, LouisSeranne approved these changes
Changements mineurs : 
- [ ] Les boutons de suppressions de noeuds ne doivent pas apparaître si ne noeud ne peut pas être supprimé
- [x] Le bouton de "liaison à un autre noeud" ne dois pas apparaître sur le noeud d'origine
- [ ] Le bouton "liaison à un autre noeud" devrais fonctionner lors d'un clic sur le nom d'un autre noeud

2023-10-24 14:50 UTC, DarOli2131947 commented
## 1. Lorsque l'on bouge les nœuds, leurs position ne sauvegarde pas si on rafraichis la page après avoir fait le changement.
https://github.com/LouisSeranne/DICJ_Stimulus_A23/assets/89397446/e47ed751-a267-41d1-9356-0142e334bc26

## 2. Des bugs visuels (tearing) surviennent lorsque l'on bouge un nœud
![image](https://github.com/LouisSeranne/DICJ_Stimulus_A23/assets/89397446/e7754a0f-80f5-4ba8-b118-8c601fc17bfe)

## 3. Lorsque le rayon est plus haut que 40, les boutons supprimer et ajouter se place incorrectement
![image](https://github.com/LouisSeranne/DICJ_Stimulus_A23/assets/89397446/024745e5-1f79-43b8-bf9b-7d2335092644)

## 4. Status devrait être une dropbox plutôt qu'un input field **(Quality of Life)**
![image](https://github.com/LouisSeranne/DICJ_Stimulus_A23/assets/89397446/a26e2d7f-e3cc-4515-8cad-5f4bb942a9b6)

2023-10-24 14:57 UTC, YohanTremblay approved these changes

2023-10-24 15:41 UTC, merged